import type { Product } from "@/lib/products/schema"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: 'MacBook Pro 14"',
    sku: "MBP14M3PRO",
    description: "Laptop z procesorem M3 Pro, 18 GB RAM, 512 GB SSD.",
    manufacturer: "Apple",
    category: "Komputery",
    features: ["Bluetooth", "WiFI", "USB-C", "Premium"],
    priceNet: 8129.27,
    priceGross: 9999,
    vatRate: 23,
    currency: "PLN",
    available: true,
    limited: false,
    stock: null,
    minCartQty: 1,
    maxCartQty: 5,
  },
  {
    id: "2",
    name: "Galaxy S24 Ultra",
    sku: "SGS24U256",
    description: "Smartfon z ekranem 6,8 cala i rysikiem S Pen, 256 GB.",
    manufacturer: "Samsung",
    category: "Telefony",
    features: ["Bluetooth", "WiFI", "USB-C", "Wodoodporny", "Premium"],
    priceNet: 5121.14,
    priceGross: 6299,
    vatRate: 23,
    currency: "PLN",
    available: true,
    limited: true,
    stock: 45,
    minCartQty: 1,
    maxCartQty: 3,
  },
  {
    id: "3",
    name: "Sony WH-1000XM5",
    sku: "SNWH1000XM5",
    description: "Bezprzewodowe słuchawki nauszne z ANC.",
    manufacturer: "Sony",
    category: "RTV",
    features: ["Bluetooth", "Bezprzewodowy", "Premium"],
    priceNet: 1300,
    priceGross: 1599,
    vatRate: 23,
    currency: "PLN",
    available: true,
    limited: false,
    stock: null,
    minCartQty: 1,
    maxCartQty: 10,
  },
  {
    id: "4",
    name: "Bosch Serie 6 WAU28P40",
    sku: "BSWAU28P40",
    description: "Pralka ładowana od przodu, 9 kg, klasa A.",
    manufacturer: "Bosch",
    category: "AGD",
    features: ["Ekologiczny"],
    priceNet: 2682.11,
    priceGross: 3299,
    vatRate: 23,
    currency: "PLN",
    available: false,
    limited: true,
    stock: 0,
    minCartQty: 1,
    maxCartQty: 2,
  },
  {
    id: "5",
    name: "Xiaomi Smart Band 8",
    sku: "XMSB8BLK",
    description: "Opaska fitness z wyświetlaczem AMOLED.",
    manufacturer: "Xiaomi",
    category: "Akcesoria",
    features: ["Bluetooth", "Wodoodporny", "Bezprzewodowy"],
    priceNet: 145.53,
    priceGross: 179,
    vatRate: 23,
    currency: "PLN",
    available: true,
    limited: false,
    stock: null,
    minCartQty: 1,
    maxCartQty: 20,
  },
  {
    id: "6",
    name: "Dyson V15 Detect",
    sku: "DYSV15DET",
    description: "Odkurzacz bezprzewodowy z laserowym wykrywaniem kurzu.",
    manufacturer: "Dyson",
    category: "AGD",
    features: ["Bezprzewodowy", "Premium"],
    priceNet: 3007.32,
    priceGross: 3699,
    vatRate: 23,
    currency: "PLN",
    available: true,
    limited: true,
    stock: 12,
    minCartQty: 1,
    maxCartQty: 2,
  },
  {
    id: "7",
    name: "Logitech MX Master 3S",
    sku: "LGMXM3S",
    description: "Ergonomiczna mysz bezprzewodowa dla profesjonalistów.",
    manufacturer: "Logitech",
    category: "Akcesoria",
    features: ["Bluetooth", "USB-C", "Bezprzewodowy"],
    priceNet: 405.69,
    priceGross: 499,
    vatRate: 23,
    currency: "PLN",
    available: true,
    limited: false,
    stock: null,
    minCartQty: 1,
    maxCartQty: 10,
  },
]
